### ISSUE TITLE
Create a seeder script to populate the database

### ISSUE THREAD

**Issue by dev-xero** [dev-xero/molla-backend#1]
# Create a seeder script to populate the database

The database needs to be populated with some pre-defined data, to allow querying by id or routes.

## TASKS

- [x] Seed the database
- [x] Write endpoints to retrieve products by their ids

**Comment by dev-xero** [comment]
- [x] Also add endpoints to get all products.

**Comment by dev-xero** [comment]
✅ **All done**
